version: '3.4'

networks:
  chart_room_net:
    external: true

services:
  server:
    image: chart-room/server
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - chart_room_net
    ports:
      - 8081:8081
  web:
    image: chart-room/www
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - chart_room_net
    depends_on:
      - server
